<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="ac5cb39a-7f7f-4569-9e2d-100d9a8d8ba7" name="fora@DELL 2015-08-18 03:57:45" runUser="dell\fora" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="ae7f9b34-cdf6-4f5e-886b-aeb8da462ab8">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="fora_DELL 2015-08-18 03_57_45">
      <DeploymentItem filename="B:\студия\Курсы C#\Task4\Data\Contacts\Contacts\Contacts\bin\Debug\Contacts.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2015-08-18T03:57:45.7548148+06:00" queuing="2015-08-18T03:57:46.8309849+06:00" start="2015-08-18T03:57:46.9390608+06:00" finish="2015-08-18T03:57:53.5439667+06:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="DELL" outcome="Error" timestamp="2015-08-18T03:57:53.5429667+06:00">
        <Text>Test host process exited unexpectedly.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="ChangeCardNameTest_CheckNameEmptyException" storage="b:\студия\курсы c#\task4\data\contacts\contacts\unittest\bin\debug\unittest.dll" id="bb9dd28b-c4c3-c7d7-57b9-f57164bc92e2">
      <Execution id="e5613183-1db1-4099-9fd7-6e36164980af" />
      <TestMethod codeBase="B:/студия/Курсы C#/Task4/Data/Contacts/Contacts/Unittest/bin/Debug/Unittest.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Unittest.CardTest, Unittest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="ChangeCardNameTest_CheckNameEmptyException" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="bb9dd28b-c4c3-c7d7-57b9-f57164bc92e2" executionId="e5613183-1db1-4099-9fd7-6e36164980af" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="e5613183-1db1-4099-9fd7-6e36164980af" testId="bb9dd28b-c4c3-c7d7-57b9-f57164bc92e2" testName="ChangeCardNameTest_CheckNameEmptyException" computerName="DELL" duration="00:00:06.5178425" startTime="2015-08-18T03:57:47.0261242+06:00" endTime="2015-08-18T03:57:53.5439667+06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e5613183-1db1-4099-9fd7-6e36164980af">
    </UnitTestResult>
  </Results>
</TestRun>