<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="4a81aa0d-8e23-41b8-a211-641f61aff6bd" name="fora@DELL 2015-08-18 02:10:15" runUser="dell\fora" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="ae7f9b34-cdf6-4f5e-886b-aeb8da462ab8">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="fora_DELL 2015-08-18 02_10_15">
      <DeploymentItem filename="B:\студия\Курсы C#\Task4\Data\Contacts\Contacts\Contacts\bin\Debug\Contacts.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2015-08-18T02:10:15.3234232+06:00" queuing="2015-08-18T02:10:15.3485032+06:00" start="2015-08-18T02:10:15.3555079+06:00" finish="2015-08-18T02:10:15.6297027+06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="CardConstructorTest_CheckNameEmptyException" storage="b:\студия\курсы c#\task4\data\contacts\contacts\unittest\bin\debug\unittest.dll" id="cb35465e-f65e-c08d-4301-04b728801d65">
      <Execution id="cdca72dc-3d24-43ba-98c1-bba683cd7f5d" />
      <TestMethod codeBase="B:/студия/Курсы C#/Task4/Data/Contacts/Contacts/Unittest/bin/Debug/Unittest.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Unittest.CardTest, Unittest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="CardConstructorTest_CheckNameEmptyException" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="cb35465e-f65e-c08d-4301-04b728801d65" executionId="cdca72dc-3d24-43ba-98c1-bba683cd7f5d" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="cdca72dc-3d24-43ba-98c1-bba683cd7f5d" testId="cb35465e-f65e-c08d-4301-04b728801d65" testName="CardConstructorTest_CheckNameEmptyException" computerName="DELL" duration="00:00:00.0394005" startTime="2015-08-18T02:10:15.3585103+06:00" endTime="2015-08-18T02:10:15.6176960+06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="cdca72dc-3d24-43ba-98c1-bba683cd7f5d">
      <Output>
        <ErrorInfo>
          <Message>Test method Unittest.CardTest.CardConstructorTest_CheckNameEmptyException did not throw expected exception System.ArgumentNullException. Сервис не вернул сообщение об ошибке при создании карточки с пустым полем Name</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>